# Generated by Django 5.2.4 on 2026-01-13 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webauthn', '0002_remove_authorization_permissions_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authorization',
            old_name='client_id',
            new_name='client',
        ),
        migrations.RenameField(
            model_name='authorization',
            old_name='user_id',
            new_name='user',
        ),
    ]
