# Generated by Django 5.2.4 on 2026-04-04 05:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webauthn', '0003_rename_client_id_authorization_client_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorization',
            name='access_token',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='authorization',
            name='auth_code',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='authorization',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webauthn.authclient'),
        ),
        migrations.AlterField(
            model_name='authorization',
            name='code_issued_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='authorization',
            name='refresh_token',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='authorization',
            name='token_issued_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='authorization',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
